controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

rest_controller:
    resource: ../src/Controller/Api/
    type: attribute
    prefix: /api
